file_format: "1"
id: proXiao
name: proXiao
type: shield
url: https://github.com/aroum/proXiao/
requires: [seeeduino_xiao_ble]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - proXiao_left
  - proXiao_right
